polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<str:ref>', views.verifyPayment, name='verifypayment')

]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import LandingPage

urlpatterns = [
    path('',LandingPage ),
    path('dashboard/', include('dashboard.urls')),
    path('polls/', include('polls.urls')),
    path('ussd/', include('ussd.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

ussd/urls.py
from django.urls import path

from . import views

app_name = 'ussd'
urlpatterns = [
    path('', views.ussdvote, name='index'),  # ussdvote  
    #wenhook post
    path('webhook', views.verify_payment, name='wenhook'),
    path('manual/verify', views.manualverify, name='manualverify'),
]

polls/models.py
from django.db import models
from .utils import unique_slug_generator
from django.dispatch import receiver


class Question(models.Model):
    id = models.AutoField(primary_key=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Contestant(models.Model):
    id = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=200)
    code =  models.SlugField(max_length=200,unique=True ,null=True ,blank=True)

    def __str__(self):
        return f'{self.Name} {self.code}'

  




class Choice(models.Model):
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.ForeignKey(Contestant, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text.Name


class webPayment(models.Model):
    id = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    amount = models.IntegerField(default=0)
    email = models.CharField(max_length=200)
    question_id = models.IntegerField(default=0)
    choice = models.CharField(max_length=200)
    reference = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.Name


        
        
@receiver(models.signals.pre_save, sender=Contestant)
def auto_slug_generator(sender, instance, **kwargs):
    """
    Creates a slug if there is no slug.
    """
    if not instance.code:
        instance.code = unique_slug_generator(instance)
        
      
   

polls/views.py
import json
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from rest_framework.response import Response
import requests
from .models import Question, Choice , webPayment

#Landing page 
def LandingPage(request):
  return render(request, 'pages/index.html')


# Get questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Show specific question and choices
def detail(request, question_id):
  try:
    question = Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'polls/detail.html', { 'question': question })

# Get question and display results
def results(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'polls/results.html', { 'question': question })

# Vote for a question choice
def vote(request, question_id):
    if request.method=='POST':
      Name =request.POST['fullName']
      phone=request.POST['phonenumber']
      amount=request.POST['amount']
      email=request.POST['email']
      
      question = get_object_or_404(Question, pk=question_id)

      # print(amount)

      #throw error to front page if choice is not selected
      try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
      except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

      return render(request, 'polls/payment.html',{"email":email,'phone':phone,'amount':amount,'question_id':question_id,'choice':request.POST['choice'],'Name':Name})

    
def verifyPayment(request,ref: str) -> HttpResponse:
  amount = request.POST['amount']
  choice = request.POST['choice']
  phone = request.POST['phone']
  email = request.POST['email']
  Name = request.POST['Name']
  question_id = request.POST['question_id']
  reference = ref
  status, response = verify_payment(reference)
  
  if status:
      question = get_object_or_404(Question, pk=question_id)
      question.choice_set.get(pk=choice) 
      selected_choice = question.choice_set.get(pk=choice)

      votesToAdd = int(amount) / 0.5
      selected_choice.votes += votesToAdd
      selected_choice.save()
     
     
      webPayment.objects.create(Name=Name,phone=phone,amount=amount,email=email,question_id=question_id,choice=choice,reference=reference,status=status,verified=True)
      return HttpResponse(question_id)
  else:
      webPayment.objects.create(Name=Name,phone=phone,amount=amount,email=email,question_id=question_id,choice=choice,reference=reference,status=status,verified=False)
      return HttpResponse(False)



def verify_payment(ref):
      base_url = 'https://api.paystack.co'
      path = f'/transaction/verify/{ref}'
      headers = {
            'Authorization': f'Bearer sk_live_49802921ecd505a560da644607d0f8f7bd782efb',
            'Content-Type': 'application/json',
        }
      url = base_url + path
      response = requests.get(url, headers=headers)
      if response.status_code == 200:
          response_data = response.json()
          return response_data['status'], response_data['data']
      response_data = response.json()
      return response_data['status'], response_data['message']

templates/polls/detail.html
{% extends 'base.html' %} {% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}"
  >Back To Polls</a
>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
  <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form
  id="paymentForm"
  action="{% url 'polls:vote' question.id %}"
  method="post"
>
  {% csrf_token %}

  <!-- Modal -->
  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Enter your Details to pay
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label"
              >Email address</label
            >
            <input
              type="email"
              class="form-control"
              id="exampleFormControlInput1"
              name="email"
              placeholder="Enter your Email name@example.com"
              required
            />
            <label for="exampleFormControlInput2" class="form-label"
              >Full name</label
            >
            <input
              type="text"
              class="form-control"
              name="fullName"
              id="exampleFormControlInput2"
              placeholder="Enter Your Full Name"
              required
            />
            <label for="exampleFormControlInput3" class="form-label"
              >Amount To pay</label
            >
            <input
              type="number"
              class="form-control"
              name="amount"
              id="exampleFormControlInput3"
              placeholder="Enter Your Amount to vote"
              required
            />

            <label for="exampleFormControlInput4" class="form-label"
              >Phone Number</label
            >

            <input
              type="decimal"
              class="form-control"
              name="phonenumber"
              id="exampleFormControlInput4"
              placeholder="Enter Your Phone Number"
              required
            />
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <button type="submit" class="btn btn-primary">Pay Now</button>
        </div>
      </div>
    </div>
  </div>

  {% for choice in question.choice_set.all %}
  <div class="form-check">
    <input
      type="radio"
      name="choice"
      class="form-check-input"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}"
      >{{ choice.choice_text.Name }}</label
    >
  </div>
  {% endfor %}
  <input
    value="Vote"
    class="btn btn-success btn-lg btn-block mt-4"
    data-bs-toggle="modal"
    data-bs-target="#exampleModal"
  />
</form>

{% endblock %}

templates/polls/index.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center mb-3">Contest</h1>
{% if latest_question_list %} {% for question in latest_question_list %}
<div class="card mb-3">
  <div class="card-body">
    <p class="lead">{{ question.question_text }}</p>
    <a
      href="{% url 'polls:detail' question.id %}"
      class="btn btn-primary btn-sm"
      >Vote Now</a
    >
    <a
      href="{% url 'polls:results' question.id %}"
      class="btn btn-secondary btn-sm"
      >Results</a
    >
  </div>
</div>
{% endfor %} {% else %}
<p>No polls available</p>
{% endif %} {% endblock %}

templates/polls/payment.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>Document</title>
  </head>
  <body onload="payWithPaystack()">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
      window.onload = function () {
        payWithPaystack();
      };
      function payWithPaystack() {
        var handler = PaystackPop.setup({
          key: "pk_live_b74739edf24cd768a29cc124a73c240499760c5f",
          email: "{{email}}",
          amount: "{{amount}}00",
          currency: "GHS",
          metadata: {
            custom_fields: [
              {
                display_name: "Mobile Number",
                variable_name: "mobile_number",
                value: "{{phone}}",
              },
            ],
          },
          callback: function (response) {
            $.post(
              "http://127.0.0.1:8000/polls/" + response.reference,
              {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                reference: response.reference,
                amount: "{{amount}}",
                email: "{{email}}",
                phone: "{{phone}}",
                Name: "{{Name}}",
                question_id: "{{question_id}}",
                choice: "{{choice}}",
              },
              function (data, status) {
                // alert("Data: " + data + "\nStatus: " + status);

                if (data == "False") {
                  alert("Payment unsuccessful");
                } else {
                  window.location.assign(
                    `http://127.0.0.1:8000/polls/${data}/results`
                  );
                }
              }
            );
          },
          onClose: function () {
            alert("window closed");
          },
        });
        handler.openIframe();
      }
    </script>
  </body>
</html>

templates/polls/results.html
{% extends 'base.html' %} {% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
  {% for choice in question.choice_set.all %}
  <li class="list-group-item">
    {{ choice.choice_text.Name }}
    <span class="badge badge-success float-right"
      >{{ choice.votes }} vote{{ choice.votes | pluralize }}</span
    >
  </li>
  {% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}"
  >Vote again?</a
>
{% endblock %}