dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('login/', views.loginAdmin, name='login'),
    path('', views.index, name='home'),
    path('questions/', views.Questions, name='questions'),
    path('contestants/', views.Contestants, name='contestants'),
    path('logout', views.LogoutOut, name='logout'),
  
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import LandingPage

urlpatterns = [
    path('',LandingPage ),
    path('dashboard/', include('dashboard.urls')),
    path('polls/', include('polls.urls')),
    path('ussd/', include('ussd.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

ussd/urls.py
from django.urls import path

from . import views

app_name = 'ussd'
urlpatterns = [
    path('', views.ussdvote, name='index'),  # ussdvote  
    #wenhook post
    path('webhook', views.verify_payment, name='wenhook'),
    path('manual/verify', views.manualverify, name='manualverify'),
]

templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: white" href="/"
      ><img height="50" width="" src="{% static 'img/ghaa.jpeg' %}" />
      GMAAWARDS</a
    >

    {% if user.is_authenticated %}

    <a
      href="{% url 'dashboard:logout' %}"
      type="button"
      class="btn btn-warning"
    >
      Logout
    </a>

    {% else %}{% endif %}
  </div>
</nav>