dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('login/', views.loginAdmin, name='login'),
    path('', views.index, name='home'),
    path('questions/', views.Questions, name='questions'),
    path('contestants/', views.Contestants, name='contestants'),
    path('logout', views.LogoutOut, name='logout'),
  
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import LandingPage

urlpatterns = [
    path('',LandingPage ),
    path('dashboard/', include('dashboard.urls')),
    path('polls/', include('polls.urls')),
    path('ussd/', include('ussd.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

ussd/urls.py
from django.urls import path

from . import views

app_name = 'ussd'
urlpatterns = [
    path('', views.ussdvote, name='index'),  # ussdvote  
    #wenhook post
    path('webhook', views.verify_payment, name='wenhook'),
    path('manual/verify', views.manualverify, name='manualverify'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth import authenticate , logout , login
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.models import User 
from django.views.decorators.csrf import csrf_protect
from polls.models import *
from ussd.models import PaymentSuccess


# Create your views here.


def loginAdmin(request): 
    if request.user.is_authenticated:
        print("authenticated")
        return redirect("dashboard:home")

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return  redirect('dashboard:home')
            else:
                return render(request, 'dashboard/login.html',{'error_message': "Your account has been disabled"})
        else:
            return render(request, 'dashboard/login.html',{'error_message': "Invalid login credentials"})

    return render(request, 'dashboard/login.html')


@login_required(login_url='/dashboard/login/')
def index(request):
    totalQC={
        'total_contestants': Contestant.objects.count(),
        'total_questions': Question.objects.count(),
    }

    moneyVotes={
        'total_votes': 0,
        'total_amount': 0
    }

    for i in webPayment.objects.all():
        if i.verified:
            moneyVotes['total_votes'] += 1
            moneyVotes['total_amount'] += i.amount
        else:
            pass

    for um in PaymentSuccess.objects.all():
            moneyVotes['total_votes'] += 1
            moneyVotes['total_amount'] += um.amount
       
        
    return render(request, 'dashboard/index.html' , {'totalQC':totalQC , 'moneyVotes':moneyVotes})


@login_required(login_url='/dashboard/login/')
def Questions(request):
    questions = Question.objects.all()
    return render(request, 'dashboard/question.html',{'questions':questions})

@login_required(login_url='/dashboard/login/')
def Contestants(request):
    contestants = Contestant.objects.all()
    data =[]
    for contestant in contestants:
        choices = Choice.objects.filter(choice_text=contestant.id)
        for c in choices:
            data.append(c)

    return render(request, 'dashboard/contestant.html',{'choices':data})

# @login_required(login_url='/dashboard/login/')
# def webPayments(request):
#     payments = webPayment.objects.all()
#     return render(request, 'dashboard/webPayment.html',{'payments':payments})



def LogoutOut(request):
    logout(request)
    return redirect('dashboard:login')

templates/dashboard/contestant.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="text-center">
  <a  href="{% url "dashboard:home" %}">
     <button type="button" class="btn btn-primary">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="50"
      height="50"
      fill="currentColor"
      class="bi bi-backspace-fill"
      viewBox="0 0 16 16"
      style="color: white"
    >
      <path
        d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"
      /></svg
    >Back
  </button>

  </a>
 
  <div class="card-body">
    <h1>contestant</h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Contesting For</th>
        <th scope="col">unique code</th>
      </tr>
    </thead>
    <tbody>
      {% for c in choices%}
      <tr>
        <td>{{c.choice_text.Name}}</td>
        <td>{{c.question.question_text}}</td>
        <td>{{c.choice_text.code}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% endblock %} x
</div>

templates/dashboard/index.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="text-center">
  <div class="card-body">
    <h1>Home Dashboard</h1>
  </div>

  <div class="row">
    <div class="col" style="padding-top: 50px">
      <div
        class="card"
        style="width: 18rem; background-color: DodgerBlue; color: white"
      >
        <div class="card-body">
          <h5 class="card-title">Amount Made</h5>
          <p class="card-text">{{moneyVotes.total_amount}}</p>
          <a
            href="#"
            style="text-decoration: none; color: white"
            class="card-link"
          ></a>
        </div>
      </div>
    </div>
    <div class="col" style="padding-top: 50px">
      <div
        class="card"
        style="width: 18rem; background-color: SlateBlue; color: white"
      >
        <div class="card-body">
          <h5 class="card-title">Total people who Voted</h5>
          <p class="card-text">{{moneyVotes.total_votes}}</p>

          <a
            href="#"
            style="text-decoration: none; color: white"
            class="card-link"
          ></a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col" style="padding-top: 50px">
      <div
        class="card"
        style="width: 18rem; background-color: Violet; color: white"
      >
        <div class="card-body">
          <h5 class="card-title">Contestant</h5>

          <p class="card-text">{{totalQC.total_contestants}}</p>
          <a
            href="{% url 'dashboard:contestants' %}"
            style="text-decoration: none; color: white"
            class="card-link"
            >view</a
          >
        </div>
      </div>
    </div>
    <div class="col" style="padding-top: 50px">
      <div
        class="card"
        style="width: 18rem; background-color: Orange; color: white"
      >
        <div class="card-body">
          <h5 class="card-title">Categories</h5>
          <p class="card-text">{{totalQC.total_questions}}</p>
          <a
            href="{% url 'dashboard:questions' %}"
            style="text-decoration: none; color: white"
            class="card-link"
            >view</a
          >
        </div>
      </div>
    </div>
  </div>

  {% endblock %} x
</div>

templates/dashboard/login.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="text-center">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="text-center text-dark mt-5">Login Form</h2>
      <div class="text-center mb-5">
        {% if error_message %}
        <p class="alert alert-danger">
          <strong>{{ error_message }}</strong>
        </p>
        {% endif %}
      </div>
      <div>
        <form method="POST" action="{% url 'dashboard:login'%}">
          {% csrf_token %}
          <div class="text-center">
            <img
              src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png"
              class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
              width="200px"
              alt="profile"
            />
          </div>

          <div class="mb-3 row">
            <label for="sername" class="col-sm-2 col-form-label"
              >Username</label
            >
            <input
              type="text"
              class="form-control"
              id="Username"
              aria-describedby="emailHelp"
              placeholder="User Name"
              name="username"
            />
          </div>
          <div class="mb-3 row">
            <label for="password" class="col-sm-2 col-form-label"
              >password</label
            >
            <input
              name="password"
              type="password"
              class="form-control"
              id="password"
              placeholder="password"
            />
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary px-5 mb-5 w-100">
              Login
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/dashboard/question.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="text-center">
  <a  href="{% url "dashboard:home" %}">
     <button type="button" class="btn btn-primary">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="50"
      height="50"
      fill="currentColor"
      class="bi bi-backspace-fill"
      viewBox="0 0 16 16"
      style="color: white"
    >
      <path
        d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"
      /></svg
    >Back
  </button>

  </a>
 
  <div class="card-body">
    <h1>Categories</h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Categories</th>
      </tr>
    </thead>
    <tbody>
      {% for q in questions%}
      <tr>
        <td>{{q.question_text}}</td>
    
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% endblock %} x
</div>